version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"