logging:
  level:
    uk:
      nhs:
        adaptors:
          oneoneone:
            cda:
              report: ${LOG_LEVEL:DEBUG}
server:
  error:
    include-message: always
amqp:
  broker: ${PEM111_AMQP_BROKER:amqp://localhost:5672}
  queueName: ${PEM111_AMQP_QUEUE_NAME:encounter-report}
  exchange: ${PEM111_AMQP_EXCHANGE:amq.direct}
  username: ${PEM111_AMQP_USERNAME:admin}
  password: ${PEM111_AMQP_PASSWORD}
  protocol: ${PEM111_AMQP_PROTOCOL:1.0} # for Rabbit MQ set to 0-9-1
  port: ${PEM111_AMQP_PORT:5672}
  sslEnabled: ${PEM111_AMQP_SSL_ENABLED:false}
  amqpRoutingKey: ${PEM111_AMQP_ROUTING_KEY:1sD23FvBgT}

soap:
  validationEnabled: ${PEM111_SOAP_VALIDATION_ENABLED:false}
  sendTo: ${PEM111_SOAP_SEND_TO:http://localhost:8080/report}

itk:
  odsCodes: ${PEM111_ITK_ODS_CODE_LIST:}
  dosIds: ${PEM111_ITK_DOS_ID_LIST:}
  externalConfigurationServiceUrl: ${PEM111_ITK_EXTERNAL_CONFIGURATION_URL:}
  fetchIntervalMinutes: ${PEM111_ITK_FETCH_INTERVAL_MIN:5}

version: ${PEM111_VERSION:1.0.3}
