logging:
  level:
    uk:
      nhs:
        adaptors:
          oneoneone:
            cda:
              report: ${LOG_LEVEL}
amqp:
  broker: ${PEM111_AMQP_BROKER:amqp://localhost:5672}
  queueName: ${PEM111_AMQP_QUEUE_NAME:encounter-report}
  exchange: amq.direct
  username: ${PEM111_AMQP_USERNAME:}
  password: ${PEM111_AMQP_PASSWORD:}