version: '3.8'
services:
  integration-adaptor-111:
    build:
      context: ../
      dockerfile: ./docker/service/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PEM111_AMQP_BROKER=amqp://activemq:5672
      - PEM111_ITK_EXTERNAL_CONFIGURATION_URL=http://wiremock:8080/configuration/ods-dos
      - LOG_LEVEL=DEBUG
    depends_on:
      - activemq
      - wiremock
    networks:
      - 111network

  activemq:
    build: ./activemq
    ports:
      - "5672:5672"
      - "8161:8161"
    networks:
      - 111network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - 111network

  wiremock:
    build: ./wiremock
    ports:
      - "8110:8080"
    command:
      - -global-response-templating
    networks:
      - 111network

  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8443:443"
      - "8480:80"
    networks:
      - 111network
    links:
      - "integration-adaptor-111:adapter"
    depends_on:
      - integration-adaptor-111
      - crl-server
    environment:
      - NGINX_ADAPTER_HOSTNAME=adapter
      - NGINX_ADAPTER_PORT=8080
      - NGINX_PUBLIC_CERT
      - NGINX_PRIVATE_CERT
      - NGINX_CLIENT_PUBLIC_CERT
      - NGINX_CA_CERT
      - NGINX_CRL
      - NGINX_CRL_URL
      - DEBUG=true
      - RUN_IN_DOCKER=true
      - SERVICE_HEALTHCHECK=/actuator/health

  crl-server:
    build:
      context: ../
      dockerfile: ./docker/crl/Dockerfile
    ports:
      - "8580:3000"
    networks:
      - 111network

networks:
  111network:
    external: true