version: '3.8'
services:
  integration-adaptor-111:
    container_name: integration-adaptor-111_tests
    build:
      target: build
    entrypoint: "gradle check"
    environment:
      - PEM111_AMQP_BROKER=activemq
      - PEM111_AMQP_PORT=5672
      - PEM111_ITK_EXTERNAL_CONFIGURATION_URL=http://wiremock:8080/configuration/ods-dos




