version: '3.8'
services:
  integration-adaptor-111:
    container_name: integration-adaptor-111_tests
    build:
      target: build
    entrypoint: "gradle check"
    environment:
      - PEM111_AMQP_BROKER=amqp://activemq:5672
      - PEM111_ITK_EXTERNAL_CONFIGURATION_URL=http://wiremock:8080/configuration/ods-dos
#      - PS_DB_URL
#      - GPC_FACADE_USER_DB_PASSWORD
#      - PS_AMQP_BROKER

#  gp2gp_translator:
#    container_name: gp2gp_translator_tests
#    build:
#      target: build
#    entrypoint: "gradle check"
#    environment:
#      - GP2GP_TRANSLATOR_SERVER_PORT
#      - PS_DB_URL
#      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
#      - PS_AMQP_BROKER
#      - MHS_AMQP_BROKER
#      - PS_QUEUE_NAME
#      - MHS_QUEUE_NAME
#      - PS_AMQP_USERNAME
#      - PS_AMQP_PASSWORD
#      - PS_AMQP_MAX_REDELIVERIES
#      - MHS_AMQP_USERNAME
#      - MHS_AMQP_PASSWORD
#      - MHS_AMQP_MAX_REDELIVERIES
#
#  common_modules:
#    container_name: common_modules_checks
#    build:
#      context: ../
#      dockerfile: ./docker/common-modules/Dockerfile



