on:
  release:
    types: [published]

jobs:
  push_to_dockerhub:
    strategy:
      matrix:
        config:
          - folder: docker/service
            dockerhub_name: nia-111-adaptor
            upload_url: ${{ github.event.release.upload_url }}
          - folder: docker/nginx
            dockerhub_name: nia-111-nginx-adaptor
            upload_url: ${{ github.event.release.upload_url }}
    uses: NHSDigital/integration-adaptor-actions/.github/workflows/release-adaptor-container-image.yml@main
    with:
      folder: ${{ matrix.config.folder }}
      dockerhub_name: ${{ matrix.config.dockerhub_name }}
      upload_url: ${{ matrix.config.upload_url }}
    secrets: inherit

